In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

arr = np.array(l)

In [3]:
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.asarray(l)  # it also creates the same array

array([1, 2, 3, 4, 5, 6])

In [12]:
arr1 = np.array([[1,2,3],[2,3,4]])

               # columns

             #   0   1   2  <--  x - axis    
      # rows-0 [ 1 , 2 , 3 ]

# y-axis --> 1 [ 2 , 3 , 4 ]  


In [8]:
type(arr1)

numpy.ndarray

In [9]:
# check the dimension of both array

arr.ndim

1

In [10]:
arr1.ndim

2

In [19]:
arr2 = np.matrix(l)  # it will return an array of min 2 dimemsion

In [20]:
arr2

matrix([[1, 2, 3, 4, 5, 6]])

In [16]:
arr2.ndim

2

In [17]:
type(arr2)

numpy.matrix

In [21]:
np.asanyarray(l)  # it aslo creates an array

array([1, 2, 3, 4, 5, 6])

In [23]:
np.asanyarray(arr2)  # it wil make no changes

# because asanyarray() is a function which is able to convert those things into an array which are present in other forms other than array.

#  matrix is a type of array , so this function will not make any changes

matrix([[1, 2, 3, 4, 5, 6]])

In [24]:
arr

array([1, 2, 3, 4, 5, 6])

In [25]:
a = arr

In [26]:
a

array([1, 2, 3, 4, 5, 6])

In [27]:
arr[0] = 100  # it will also make changes in the "a" and this copying is called 'solo copying'

In [28]:
arr

array([100,   2,   3,   4,   5,   6])

In [29]:
a  

array([100,   2,   3,   4,   5,   6])

In [30]:
b = arr.copy()

In [31]:
b

array([100,   2,   3,   4,   5,   6])

In [32]:
arr[0] = 1  # it will not make changes to "b"  bcs a new memory space is created and copy the array into it

#  this level of copying is called 'Deep Copying'

In [33]:
arr

array([1, 2, 3, 4, 5, 6])

In [34]:
b

array([100,   2,   3,   4,   5,   6])

In [35]:
#  some functions

In [36]:
arr3 = np.fromfunction(lambda i ,j : i==j , (3,3))  # (3,3) = shape [ 3 rows , 3 columns ]

In [37]:
arr3

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [38]:
arr4 = np.fromfunction(lambda x , y : x * y , (3,3))

In [39]:
arr4

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [40]:
list(i**2 for i in range(5))

[0, 1, 4, 9, 16]

In [45]:
#  some kind of operations we want to do to make array

iterable = ( i**2 for i in range(5))
np.fromiter(iterable , int)

array([ 0,  1,  4,  9, 16])

In [46]:
np.fromstring("2 3 4 5 6 " , sep = (" "))

array([2., 3., 4., 5., 6.])

In [48]:
np.fromstring("2,3,4,5,6" , sep = (",") , dtype = int)

array([2, 3, 4, 5, 6])

In [49]:
arr

array([1, 2, 3, 4, 5, 6])

In [51]:
np.shape(arr)  # or arr.shape

(6,)

In [52]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [53]:
np.shape(arr1)

(2, 3)

In [54]:
arr

array([1, 2, 3, 4, 5, 6])

In [55]:
np.size(arr)   # or arr.size

6

In [56]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [57]:
np.size(arr1)

6

In [58]:
arr1.ndim

2

In [59]:
arr.ndim

1

In [60]:
arr.dtype

dtype('int64')