In [3]:
import numpy as np

In [2]:
range(5)

range(0, 5)

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(0.4 , 10.4))  # it give error bcz range() takes only integer values

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
np.arange(0.4 , 10.4)  # it is just like range() but we can add floating values. 

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [7]:
np.arange(0.4 , 10.4 , 0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [8]:
list(np.arange(0.4 , 10.4 , 0.2))  # converting into list

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [11]:
# linspace() --> it will generate any given number of data between two given numbers

np.linspace(1,5,20)  # it will equally divide the numbers

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [12]:
#  logspace() --> it will generate any given number of data in log form between two numbers

In [ ]:
# bY default it take log with base 10

In [14]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [15]:
# we can set the base

np.logspace(1,5,10 , base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [16]:
# zeros()

In [17]:
np.zeros(5)  # it will generate an 1-D array of size 5 

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,3))  # it will generate an 2-D array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros((3,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [20]:
# ones()

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
arr = np.ones((3,4))

In [25]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.ones((3,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [26]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
arr+5  # it will add 5 to each index.

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [28]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [29]:
arr/2

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

In [30]:
arr-2

array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.]])

In [31]:
# empty()

In [32]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.empty((2,4,3))

array([[[4.68434417e-310, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]]])

In [34]:
#  eye() --> identity matrix

In [39]:
arr1 = np.eye(5)

In [40]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.eye(3,2)  # it will do third row elements 0

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [41]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
import pandas as pd

pd.DataFrame({"a" : arr1[0] , "b" : arr1[1] , "c" : arr1[2] , "d" : arr1[3] , "e" : arr1[4]})

a    b    c    d    e
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [44]:
#  random

In [45]:
np.random.rand(2,4)  # it will create an array of shape = (2,4)

#  It gives a dataset where mean and standard deviation can be anything

array([[0.01216871, 0.41035295, 0.75125698, 0.81916303],
       [0.79800219, 0.66950645, 0.3696503 , 0.7479257 ]])

In [46]:
np.random.randn(2,4)

# it gives you a dataset on the basis of standard normal  distribution 
# standard normal distribution [ mean = 0 ,std deviation = 1] 

array([[ 0.06588074,  1.06584275,  1.66518067, -0.15747669],
       [-0.95561982,  0.28730793, -0.03935553, -0.78961699]])

In [48]:
arr2 = np.random.randint(1,4 , (3,4))  

#  it create an array of shape = (3,4) which has elements between 1 to 4 

In [49]:
arr2

array([[1, 3, 3, 2],
       [3, 2, 2, 2],
       [3, 3, 3, 2]])

In [51]:
arr.size

12

In [50]:
arr2.shape


(3, 4)

In [56]:
#  reshape  --> the number of elements must be same

arr2.reshape(4,3)

array([[1, 3, 3],
       [2, 3, 2],
       [2, 2, 3],
       [3, 3, 2]])

In [57]:
arr2.reshape(6,2)

array([[1, 3],
       [3, 2],
       [3, 2],
       [2, 2],
       [3, 3],
       [3, 2]])

In [58]:
arr2.reshape(2,2,3)

array([[[1, 3, 3],
        [2, 3, 2]],

       [[2, 2, 3],
        [3, 3, 2]]])

In [61]:
arr2 = arr2.reshape(4,-1)  # we can write -1 , it will automatically create an array accordingly

#  they will not permanently change  the shape. for this we have to do reassignment

In [62]:
arr2

array([[1, 3, 3],
       [2, 3, 2],
       [2, 2, 3],
       [3, 3, 2]])

In [63]:
arr2 >2

array([[False,  True,  True],
       [False,  True, False],
       [False, False,  True],
       [ True,  True, False]])

In [67]:
arr2[arr2 >2]  # to filter the data 

array([3, 3, 3, 3, 3, 3])

In [68]:
arr2

array([[1, 3, 3],
       [2, 3, 2],
       [2, 2, 3],
       [3, 3, 2]])

In [69]:
arr2[0]

array([1, 3, 3])

In [70]:
arr2[0 , [1]]

array([3])

In [73]:
arr2[0 , [0 ,1]]

array([1, 3])

In [74]:
arr2[0:3 , [0 ,1]]  # just like list slicing

array([[1, 3],
       [2, 3],
       [2, 2]])

In [5]:
arr3 = np.random.randint(1,3 , (3,3))
arr4 = np.random.randint(1,3 , (3,3))

In [80]:
arr3

array([[1, 2, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [81]:
arr4

array([[1, 1, 1],
       [2, 2, 1],
       [1, 1, 2]])

In [82]:
arr3 + arr4  # it will add by index

array([[2, 3, 3],
       [4, 4, 2],
       [2, 2, 4]])

In [83]:
arr3 - arr4

array([[0, 1, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [84]:
arr3*arr4 # it is not matrix multiplication

array([[1, 2, 2],
       [4, 4, 1],
       [1, 1, 4]])

In [85]:
arr3@arr4  #  Matrix multiplication

array([[7, 7, 7],
       [7, 7, 6],
       [5, 5, 6]])

In [86]:
arr3/0

/tmp/ipykernel_1309/1466893960.py:1: RuntimeWarning: divide by zero encountered in divide
  arr3/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [6]:
arr3**arr4

array([[2, 4, 2],
       [1, 1, 1],
       [2, 1, 1]])

In [7]:
~arr3

array([[-3, -3, -3],
       [-2, -2, -2],
       [-3, -2, -2]])

In [8]:
arr3>arr4

array([[ True, False,  True],
       [False, False, False],
       [ True, False, False]])

In [9]:
arr3[arr3>arr4]

array([2, 2, 2])

In [87]:
# Numpy -Broadcasting

In [89]:
arr5 = np.zeros((3,4))

In [90]:
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [98]:
arr5 + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [97]:
arr5 * 5 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [96]:
arr5 - 5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [94]:
arr6 = np.array([1,2,3,4])

In [95]:
arr6

array([1, 2, 3, 4])

In [99]:
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [100]:
arr5 + arr6  # it will add column wise

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [101]:
# if we want to add row wise

b = np.array([3,4,5])

In [102]:
b

array([3, 4, 5])

In [114]:
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [116]:
b.T

array([3, 4, 5])

In [117]:
# sqrt()  -> square root of each elements

In [120]:
arr2

array([[1, 3, 3],
       [2, 3, 2],
       [2, 2, 3],
       [3, 3, 2]])

In [121]:
np.sqrt(arr2)

array([[1.        , 1.73205081, 1.73205081],
       [1.41421356, 1.73205081, 1.41421356],
       [1.41421356, 1.41421356, 1.73205081],
       [1.73205081, 1.73205081, 1.41421356]])

In [122]:
# log


In [123]:
np.log(arr2)

array([[0.        , 1.09861229, 1.09861229],
       [0.69314718, 1.09861229, 0.69314718],
       [0.69314718, 0.69314718, 1.09861229],
       [1.09861229, 1.09861229, 0.69314718]])

In [124]:
# exp

In [125]:
np.exp(arr2)

array([[ 2.71828183, 20.08553692, 20.08553692],
       [ 7.3890561 , 20.08553692,  7.3890561 ],
       [ 7.3890561 ,  7.3890561 , 20.08553692],
       [20.08553692, 20.08553692,  7.3890561 ]])

In [126]:
np.max(arr2)

3

In [128]:
np.mean(arr2)

2.4166666666666665

In [141]:
arr2.mean()

2.4166666666666665

In [129]:
np.min(arr2)

1

In [131]:
arr2.min()

1

In [138]:
np.var(arr2)

0.40972222222222215

In [140]:
arr2.var()

0.40972222222222215