In [2]:
import numpy as np

In [3]:
# Numpy - Array Manipulation

In [16]:
arr = np.random.randint(1,10,(4,4))

In [17]:
arr


array([[7, 7, 2, 3],
       [3, 2, 5, 3],
       [9, 7, 4, 7],
       [6, 3, 1, 2]])

In [18]:
arr.reshape(2,2,4)

array([[[7, 7, 2, 3],
        [3, 2, 5, 3]],

       [[9, 7, 4, 7],
        [6, 3, 1, 2]]])

In [19]:
arr

array([[7, 7, 2, 3],
       [3, 2, 5, 3],
       [9, 7, 4, 7],
       [6, 3, 1, 2]])

In [20]:
arr.T  # transpose

array([[7, 3, 9, 6],
       [7, 2, 7, 3],
       [2, 5, 4, 1],
       [3, 3, 7, 2]])

In [21]:
arr.flatten()  # it falttens the array to 1 D array

array([7, 7, 2, 3, 3, 2, 5, 3, 9, 7, 4, 7, 6, 3, 1, 2])

In [22]:
arr

array([[7, 7, 2, 3],
       [3, 2, 5, 3],
       [9, 7, 4, 7],
       [6, 3, 1, 2]])

In [23]:
np.expand_dims(arr , axis = 1)  # expand the dimension along column

array([[[7, 7, 2, 3]],

       [[3, 2, 5, 3]],

       [[9, 7, 4, 7]],

       [[6, 3, 1, 2]]])

In [24]:
np.expand_dims(arr ,axis=0)  # expand the dimension along row

array([[[7, 7, 2, 3],
        [3, 2, 5, 3],
        [9, 7, 4, 7],
        [6, 3, 1, 2]]])

In [25]:
data = np.array([[1],[2],[3]])

In [26]:
data

array([[1],
       [2],
       [3]])

In [27]:
data.squeeze()

array([1, 2, 3])

In [28]:
arr

array([[7, 7, 2, 3],
       [3, 2, 5, 3],
       [9, 7, 4, 7],
       [6, 3, 1, 2]])

In [29]:
arr.repeat(2)  # it repeats all elments given number of times


array([7, 7, 7, 7, 2, 2, 3, 3, 3, 3, 2, 2, 5, 5, 3, 3, 9, 9, 7, 7, 4, 4,
       7, 7, 6, 6, 3, 3, 1, 1, 2, 2])

In [30]:
np.repeat(arr,2)

array([7, 7, 7, 7, 2, 2, 3, 3, 3, 3, 2, 2, 5, 5, 3, 3, 9, 9, 7, 7, 4, 4,
       7, 7, 6, 6, 3, 3, 1, 1, 2, 2])

In [31]:
arr

array([[7, 7, 2, 3],
       [3, 2, 5, 3],
       [9, 7, 4, 7],
       [6, 3, 1, 2]])

In [32]:
np.roll(arr , shift = 1)

array([[2, 7, 7, 2],
       [3, 3, 2, 5],
       [3, 9, 7, 4],
       [7, 6, 3, 1]])

In [29]:
np.roll(arr , shift = 2)  # it shifts each element twice[forward shift]

array([[4, 4, 7, 7],
       [7, 1, 6, 6],
       [8, 8, 3, 5],
       [8, 5, 5, 5]])

AttributeError: 'numpy.ndarray' object has no attribute 'roll'

In [33]:
arr

array([[7, 7, 2, 3],
       [3, 2, 5, 3],
       [9, 7, 4, 7],
       [6, 3, 1, 2]])

In [34]:
arr.diag()

AttributeError: 'numpy.ndarray' object has no attribute 'diag'

In [35]:
np.diag(arr)

array([7, 2, 4, 2])

In [36]:
arr1 = np.array([1,2,3,4])

In [37]:
arr1

array([1, 2, 3, 4])

In [38]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [39]:
# Numpy - Stirng operations


In [40]:
arr2 = np.array(["Mohan","Sohan","Dinesh"])

In [41]:
arr2

array(['Mohan', 'Sohan', 'Dinesh'], dtype='<U6')

In [42]:
np.char.upper(arr2)

array(['MOHAN', 'SOHAN', 'DINESH'], dtype='<U6')

In [43]:
arr2.char.upper()

AttributeError: 'numpy.ndarray' object has no attribute 'char'

In [44]:
np.char.lower(arr2)

array(['mohan', 'sohan', 'dinesh'], dtype='<U6')

In [45]:
np.char.capitalize(arr2)

array(['Mohan', 'Sohan', 'Dinesh'], dtype='<U6')

In [46]:
# NUmpy - Mathematical operations

In [47]:
arr

array([[7, 7, 2, 3],
       [3, 2, 5, 3],
       [9, 7, 4, 7],
       [6, 3, 1, 2]])

In [48]:
arr.sin()

AttributeError: 'numpy.ndarray' object has no attribute 'sin'

In [49]:
arr.sin

AttributeError: 'numpy.ndarray' object has no attribute 'sin'

In [50]:
np.sin(arr)

array([[ 0.6569866 ,  0.6569866 ,  0.90929743,  0.14112001],
       [ 0.14112001,  0.90929743, -0.95892427,  0.14112001],
       [ 0.41211849,  0.6569866 , -0.7568025 ,  0.6569866 ],
       [-0.2794155 ,  0.14112001,  0.84147098,  0.90929743]])

In [51]:
np.cos(arr)

array([[ 0.75390225,  0.75390225, -0.41614684, -0.9899925 ],
       [-0.9899925 , -0.41614684,  0.28366219, -0.9899925 ],
       [-0.91113026,  0.75390225, -0.65364362,  0.75390225],
       [ 0.96017029, -0.9899925 ,  0.54030231, -0.41614684]])

In [52]:
np.tan(arr)

array([[ 0.87144798,  0.87144798, -2.18503986, -0.14254654],
       [-0.14254654, -2.18503986, -3.38051501, -0.14254654],
       [-0.45231566,  0.87144798,  1.15782128,  0.87144798],
       [-0.29100619, -0.14254654,  1.55740772, -2.18503986]])

In [53]:
np.exp(arr)

array([[1.09663316e+03, 1.09663316e+03, 7.38905610e+00, 2.00855369e+01],
       [2.00855369e+01, 7.38905610e+00, 1.48413159e+02, 2.00855369e+01],
       [8.10308393e+03, 1.09663316e+03, 5.45981500e+01, 1.09663316e+03],
       [4.03428793e+02, 2.00855369e+01, 2.71828183e+00, 7.38905610e+00]])

In [54]:
np.power(arr,2)

array([[49, 49,  4,  9],
       [ 9,  4, 25,  9],
       [81, 49, 16, 49],
       [36,  9,  1,  4]])

In [55]:
np.sqrt(arr)

array([[2.64575131, 2.64575131, 1.41421356, 1.73205081],
       [1.73205081, 1.41421356, 2.23606798, 1.73205081],
       [3.        , 2.64575131, 2.        , 2.64575131],
       [2.44948974, 1.73205081, 1.        , 1.41421356]])

In [56]:
np.mean(arr)

4.4375

In [57]:
np.median(arr)

3.5

In [58]:
np.max(arr)

9

In [59]:
np.min(arr)

1

In [60]:
np.var(arr)

5.49609375

In [61]:
np.std(arr)

2.3443749166888814

In [62]:
#  NUmpy search ,sort , counting operations

In [65]:
arr

array([[7, 7, 2, 3],
       [3, 2, 5, 3],
       [9, 7, 4, 7],
       [6, 3, 1, 2]])

In [66]:
np.sort(arr)

array([[2, 3, 7, 7],
       [2, 3, 3, 5],
       [4, 7, 7, 9],
       [1, 2, 3, 6]])

In [79]:
arr1 = np.array([1,5,3,7,6,12,2])

In [80]:
np.sort(arr1)

array([ 1,  2,  3,  5,  6,  7, 12])

In [81]:
np.searchsorted(arr1 , 9) # it give the index where the element should be placed to maintain order.

5

In [85]:
np.searchsorted(arr1 , 4)

1

In [86]:
np.searchsorted(arr1 ,8)

5

In [88]:
np.count_nonzero(arr1) # it find the total no. of non - zero elements


7

In [94]:
arr1

array([ 1,  5,  3,  7,  6, 12,  2])

In [89]:
np.where(arr1>5)  # it give the array of those indexces where the element > 5

(array([3, 4, 5]),)

In [90]:
arr

array([[7, 7, 2, 3],
       [3, 2, 5, 3],
       [9, 7, 4, 7],
       [6, 3, 1, 2]])

In [91]:
np.where(arr>5)

(array([0, 0, 2, 2, 2, 3]), array([0, 1, 0, 1, 3, 0]))

In [93]:
np.extract(arr1>5,arr1)

array([ 7,  6, 12])

In [95]:
np.extract(arr>5 ,arr)

array([7, 7, 9, 7, 7, 6])

In [96]:
#  Byte Swapping  - it converts the element into  byte form

In [97]:
arr1

array([ 1,  5,  3,  7,  6, 12,  2])

In [98]:
arr1.byteswap()

array([ 72057594037927936, 360287970189639680, 216172782113783808,
       504403158265495552, 432345564227567616, 864691128455135232,
       144115188075855872])

In [99]:
# NUmpy matrix library

In [101]:
from numpy import matlib as nm

In [102]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [103]:
nm.ones(5)

matrix([[1., 1., 1., 1., 1.]])

In [104]:
nm.linspace(1,3,5)

array([1. , 1.5, 2. , 2.5, 3. ])

In [105]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [106]:
nm.random.randint(1,4,(2,4))

array([[3, 3, 3, 3],
       [2, 1, 2, 1]])

In [ ]:
#  we can perform all the operations that we have done in numpy library